front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
front_contactpage:
    path:     /ContactUs
    defaults: { _controller: FrontBundle:Default:contactUs }
front_aboutUsPage:
    path:     /aboutUs
    defaults: { _controller: FrontBundle:Default:aboutUs }